### ISSUE TITLE
Support for italicized templates

### ISSUE THREAD

**Issue by nasikshafeek** [KennyGScott/vscode-retreon#1]
Do you wish to make the theme more italicized to make it look more elegant?

Something like in this screenshot: https://ibb.co/GPK56kF

I have the changes for the theme code, I can make a PR if you wish!

**Comment by nasikshafeek** [comment]
By the way, this is my favorite theme for a long time. Wonderful choice of colors and I love everything about this theme :)

**Comment by KennyGScott** [comment]
@kisanme Please issue a PR! I love that addition! Beautiful work. Sorry about the delayed response, lost my account for a while.

**Comment by nasikshafeek** [comment]
Thanks man.
@KennyGScott Opened a PR. Please check the referenced PR.
